### ISSUE TITLE
Parallelize benchmark.py

### ISSUE THREAD

**Issue by poorlyknitsweater** [channable/alfred-margaret#16]
Currently `benchmark.py` pins the process it measure to a single CPU anyways so it should be possible to significantly reduce benchmark waiting times by running multiple processes simultaneously, distributing the input files among them.

**Comment by fatho** [comment]
They're not as independent as it seems though. With more active cores, power consumption, and thus excess heat, will be higher, potentially forcing the CPU to lower frequencies than with just a single active core. For example, Intel says about their Turbo Boost technology that "due to varying power characteristics, some parts with Intel® Turbo Boost Technology 2.0 may not achieve maximum turbo frequencies when running heavy workloads and using multiple cores concurrently". (https://www.intel.com/content/www/us/en/architecture-and-technology/turbo-boost/turbo-boost-technology.html)

Additionally, while the cores are still somewhat independent, the CPU caches usually are not. For example, my laptop has this cache topology, and so even if you only run one benchmark per physical rather than logical core, you'll still have contention on the L3 cache.
![image](https://user-images.githubusercontent.com/3857449/155485022-c99cf002-7bff-4754-98a8-6b099fe208de.png)

---

It may still be good enough for a first guesstimate, but I'd expect more noise in the resulting data.

**Comment by poorlyknitsweater** [comment]
Sure, this would be more of an improvement for active development work, for PRs and such we should still run it on a single core.
